# Generated by Django 3.2.13 on 2023-08-05 14:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230805_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
