# Generated by Django 3.2.13 on 2023-08-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expiration',
        ),
    ]
