# Generated by Django 3.2.13 on 2023-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_history',
            field=models.JSONField(default=dict),
        ),
    ]
