# Generated by Django 3.2.13 on 2023-08-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cartitem_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
